Joao
DenegaSouza/ProjetoCadastro_Turma1 pull request #1
Opened 2022-09-22 00:46 UTC by JoaoVictorOlve

Parte 3 do projeto:
- Quando a opção de falar com atendente for selecionada, o código é executado

2022-09-22 02:47 UTC, lsebold commented on joao.py
> +atendente = ['Xuxa', 'Shakira', 'Faustão', 'Ana Maria Braga']
HAHAHAHAHAHAHAHAHA the zoeira never ends

2022-09-22 02:48 UTC, lsebold approved these changes

2022-09-23 21:17 UTC, lucasbnu0 approved these changes

2022-09-23 21:36 UTC, DenegaSouza requested changes
diminui o tempo na 2a passada pela fila, para ano ficar muito demorado.
ou sleep menor ou começar em uma posicao mais baixa na fila.

2022-09-23 21:41 UTC, Haipo31 approved these changes

2022-09-23 22:03 UTC, MQSilveira approved these changes

2022-09-23 22:04 UTC, Haipo31 approved these changes

2022-09-23 22:05 UTC, MQSilveira approved these changes

2022-09-23 22:05 UTC, MQSilveira approved these changes

2022-09-23 22:06 UTC, MQSilveira approved these changes

2022-09-23 22:06 UTC, MQSilveira approved these changes

2022-09-23 22:13 UTC, lsebold approved these changes

2022-09-23 22:13 UTC, lucasbnu0 approved these changes

2022-09-23 22:14 UTC, MQSilveira approved these changes

2022-09-23 22:17 UTC, DenegaSouza approved these changes

2022-09-23 22:26 UTC, Haipo31 approved these changes

2022-09-23 22:27 UTC, MQSilveira approved these changes

2022-09-23 22:27 UTC, lsebold approved these changes

2022-09-23 22:28 UTC, MQSilveira approved these changes

2022-09-23 22:30 UTC, DenegaSouza approved these changes

2022-09-23 23:20 UTC, merged